// AUTOGENERATED by `python -m app.ml.export_metrics`. Do not edit by hand --
// re-run the exporter after registry.json changes.
//
// Every field ml-evaluation-standards requires alongside a headline number is
// REQUIRED on HeldoutMetrics in types/metrics.ts, not optional -- a future export
// that drops one fails `tsc -b --noEmit`, which is already a CI gate. This is a type
// ANNOTATION below, not an `as` assertion -- an assertion would suppress that check.
import type { GeneratedMetrics } from '@/types/metrics'

export const METRICS: GeneratedMetrics = {
  "causal_cost": {
    "base_rate": 0.034804,
    "calibration": {
      "bins": [
        {
          "bin_lower": 0.0,
          "bin_upper": 0.1,
          "count": 82965,
          "mean_predicted": 0.011317,
          "observed_frequency": 0.014078
        },
        {
          "bin_lower": 0.1,
          "bin_upper": 0.2,
          "count": 2404,
          "mean_predicted": 0.140377,
          "observed_frequency": 0.122712
        },
        {
          "bin_lower": 0.2,
          "bin_upper": 0.30000000000000004,
          "count": 814,
          "mean_predicted": 0.244561,
          "observed_frequency": 0.237101
        },
        {
          "bin_lower": 0.30000000000000004,
          "bin_upper": 0.4,
          "count": 427,
          "mean_predicted": 0.345759,
          "observed_frequency": 0.299766
        },
        {
          "bin_lower": 0.4,
          "bin_upper": 0.5,
          "count": 305,
          "mean_predicted": 0.445562,
          "observed_frequency": 0.354098
        },
        {
          "bin_lower": 0.5,
          "bin_upper": 0.6000000000000001,
          "count": 232,
          "mean_predicted": 0.550147,
          "observed_frequency": 0.469828
        },
        {
          "bin_lower": 0.6000000000000001,
          "bin_upper": 0.7000000000000001,
          "count": 212,
          "mean_predicted": 0.65092,
          "observed_frequency": 0.462264
        },
        {
          "bin_lower": 0.7000000000000001,
          "bin_upper": 0.8,
          "count": 212,
          "mean_predicted": 0.751636,
          "observed_frequency": 0.622642
        },
        {
          "bin_lower": 0.8,
          "bin_upper": 0.9,
          "count": 254,
          "mean_predicted": 0.852716,
          "observed_frequency": 0.712598
        },
        {
          "bin_lower": 0.9,
          "bin_upper": 1.0,
          "count": 756,
          "mean_predicted": 0.967476,
          "observed_frequency": 0.887566
        }
      ],
      "brier_score": 0.022601,
      "expected_calibration_error": 0.005725,
      "fitted_on": "V-fit",
      "note": "Every cost figure in this entry is a probability multiplied by an amount, so calibration error propagates directly into cost. Fitted on V-fit; thresholds were chosen on V-late; this measurement is on test."
    },
    "cnp_regime": [
      {
        "caught_fraud_value": 70455.93,
        "confusion_matrix": {
          "fn": 2317,
          "fp": 120,
          "tn": 85378,
          "tp": 766
        },
        "cost_per_1000": 17652.23,
        "flag_rate": 0.010002,
        "missed_fraud_value": 399152.59,
        "policy": "probability",
        "precision": 0.86456,
        "recall": 0.248459,
        "recall_by_value": 0.150031
      },
      {
        "caught_fraud_value": 126123.11,
        "confusion_matrix": {
          "fn": 2355,
          "fp": 158,
          "tn": 85340,
          "tp": 728
        },
        "cost_per_1000": 17259.74,
        "flag_rate": 0.010002,
        "missed_fraud_value": 343485.41,
        "policy": "plug_in",
        "precision": 0.82167,
        "recall": 0.236134,
        "recall_by_value": 0.268571
      },
      {
        "caught_fraud_value": 98356.15,
        "confusion_matrix": {
          "fn": 2322,
          "fp": 125,
          "tn": 85373,
          "tp": 761
        },
        "cost_per_1000": 17368.31,
        "flag_rate": 0.010002,
        "missed_fraud_value": 371252.37,
        "policy": "learned_loss",
        "precision": 0.858916,
        "recall": 0.246837,
        "recall_by_value": 0.209443
      }
    ],
    "cnp_regime_deltas": [
      {
        "baseline": "probability",
        "cost_delta_ci95": [
          -582.1832,
          -145.4999
        ],
        "cost_delta_pct": -2.2235,
        "cost_delta_per_1000": -392.49,
        "policy": "plug_in",
        "verdict": "CHEAPER than the baseline"
      },
      {
        "baseline": "probability",
        "cost_delta_ci95": [
          -432.6864,
          -97.7251
        ],
        "cost_delta_pct": -1.6084,
        "cost_delta_per_1000": -283.92,
        "policy": "learned_loss",
        "verdict": "CHEAPER than the baseline"
      }
    ],
    "confusion_matrix": {
      "fn": 2598,
      "fp": 517,
      "tn": 84981,
      "tp": 485
    },
    "cost_reduction_vs_baseline": {
      "baseline": "probability",
      "cost_delta_ci95": [
        -1345.2788,
        -881.809
      ],
      "cost_delta_pct": -22.4065,
      "cost_delta_per_1000": -1098.4756,
      "flag_rate": 0.01,
      "policy": "plug_in",
      "value_recall_delta": 0.219736,
      "value_recall_delta_ci95": [
        0.183194,
        0.255257
      ],
      "verdict": "CHEAPER than the baseline"
    },
    "false_positive_cost": {
      "assumptions": [
        "Cost is linear in the number of mistakes: no queue-congestion effect, no customer-churn effect from repeated false declines, no recovery on disputed fraud. All three would raise the true cost of a false positive.",
        "Every fraud is assumed to charge back. In practice some share is never disputed, which would lower false-negative cost.",
        "Review capacity is unbounded. This is the assumption that bites hardest: the cost-minimising threshold below flags whatever share of traffic the arithmetic favours, with no ceiling on the queue it implies."
      ],
      "cost_per_1000_transactions": 3654.6277,
      "false_negative_cost": 322179.58,
      "false_negatives": 2598,
      "false_positive_cost": 1551.0,
      "false_positives": 517,
      "flag_rate": 0.011312,
      "flagged": 1002,
      "total_cost": 323730.58,
      "unit": "transaction",
      "units": "IEEE-CIS amount units (consistent with USD)"
    },
    "model_id": "causal-cost-dr-plugin-ieee-cis-20260825t045935z",
    "notes": [
      "NO TREATMENT VARIABLE EXISTS IN THIS DATA. IEEE-CIS records no action, decision, decline, review or dispute column; PaySim's isFlaggedFraud is a deterministic simulator rule firing on 16 of 6.36M rows, nested inside the label, and the pipeline drops it. Every transaction here was allowed. No causal effect is recovered from this corpus and none is claimed.",
      "Under the stated cost model both potential outcomes are deterministic given (label, amount), so the DR-Learner collapses exactly onto a cost-weighted plug-in rule driven by a calibrated probability. The proof is in the app.models.causal_cost module docstring. The DR machinery is used for off-policy EVALUATION against a SIMULATED logging policy, where the true policy cost is exactly computable and the estimators can therefore be validated rather than merely applied.",
      "Loss regression: LightGBM Tweedie (variance power 1.5) on the target Y*(amount+15.00), the same feature set as Tier-1 (113 columns). Out-of-fold over 5 forward-chaining blocks; block 1 unscored, 330,703 of 413,378 train rows carry an out-of-fold prediction.",
      "Amount reaches every model in this phase as the engineered amount_log, which is a live Tier-1 feature. The raw amount and TransactionAmt columns are on the deny list only because they are exact duplicates of it, monotone and therefore giving a tree identical splits -- not because amount is withheld. This is not leakage: the amount is known before the decision is made, which is what makes it usable in the cost arithmetic at all. The loss regression reads exactly the columns Tier-1 reads and adds nothing.",
      "The per-transaction worked examples behind the 'what this does NOT catch' section are deliberately NOT recorded here. This file is tracked in git, and ten identified transactions with their exact fraud probabilities and the features that produced them is a worked set of examples of what does and does not clear the operating threshold. The aggregate failure modes are described in notebooks/cost_report.md and app/models/README.md, which is what ml-evaluation-standards section 4 requires; the identifiers add attacker value and are required by nothing.",
      "THE HEADLINE IS REGIME-DEPENDENT. A false negative costs amount + fee, so what value-weighting exploits is the share of that cost which varies between transactions: 82.0% at the default fee of 15.00 against a median test amount of 68.50, but only 12.0% at the card-not-present fee of 500.00. Under that regime the advantage largely disappears, as the cnp_regime block records. Cost-aware ranking pays in proportion to how heterogeneous the loss is, and that is a property of a business's chargeback economics rather than of this model.",
      "Test was scored once, after all operating points were fixed on V-late. The cost matrix is the project default (review 3.00, fee 15.00) so these figures are comparable with Phases 2-5; the card-not-present regime (50/500) is reported as a separate table and selects nothing."
    ],
    "ope_validation_caveat": "The logging policy is SIMULATED and its propensity is known by construction. These figures validate the estimators; they are not a causal effect measured on this corpus, which records no historical action at all.",
    "policies": [
      {
        "caught_fraud_value": 98615.54,
        "confusion_matrix": {
          "fn": 2111,
          "fp": 231,
          "tn": 85267,
          "tp": 972
        },
        "cost_per_1000": 4553.47,
        "flag_rate": 0.013581,
        "missed_fraud_value": 370992.98,
        "policy": "probability",
        "precision": 0.80798,
        "recall": 0.315277,
        "recall_by_value": 0.209995
      },
      {
        "caught_fraud_value": 186398.94,
        "confusion_matrix": {
          "fn": 2598,
          "fp": 517,
          "tn": 84981,
          "tp": 485
        },
        "cost_per_1000": 3654.63,
        "flag_rate": 0.011312,
        "missed_fraud_value": 283209.58,
        "policy": "plug_in",
        "precision": 0.484032,
        "recall": 0.157314,
        "recall_by_value": 0.396924
      },
      {
        "caught_fraud_value": 179583.06,
        "confusion_matrix": {
          "fn": 2550,
          "fp": 547,
          "tn": 84951,
          "tp": 533
        },
        "cost_per_1000": 3724.46,
        "flag_rate": 0.012192,
        "missed_fraud_value": 290025.46,
        "policy": "learned_loss",
        "precision": 0.493519,
        "recall": 0.172884,
        "recall_by_value": 0.38241
      }
    ],
    "positives": 3083,
    "rows": 88581,
    "sensitivity": [
      {
        "factor": 0.5,
        "false_negatives": 115,
        "false_positives": 4468,
        "flag_rate": 0.227265,
        "total_cost": 13267.52,
        "varied": "both costs"
      },
      {
        "factor": 1.0,
        "false_negatives": 116,
        "false_positives": 4322,
        "flag_rate": 0.220627,
        "total_cost": 20622.97,
        "varied": "both costs"
      },
      {
        "factor": 1.5,
        "false_negatives": 127,
        "false_positives": 3966,
        "flag_rate": 0.204055,
        "total_cost": 27640.32,
        "varied": "both costs"
      },
      {
        "factor": 1.0,
        "false_negatives": 116,
        "false_positives": 4322,
        "flag_rate": 0.220627,
        "total_cost": 20622.97,
        "varied": "review cost only"
      },
      {
        "factor": 5.0,
        "false_negatives": 312,
        "false_positives": 864,
        "flag_rate": 0.055631,
        "total_cost": 47132.13,
        "varied": "review cost only"
      },
      {
        "factor": 25.0,
        "false_negatives": 489,
        "false_positives": 145,
        "flag_rate": 0.015172,
        "total_cost": 69307.64,
        "varied": "review cost only"
      },
      {
        "factor": 100.0,
        "false_negatives": 551,
        "false_positives": 23,
        "flag_rate": 0.006864,
        "total_cost": 78150.24,
        "varied": "review cost only"
      }
    ]
  },
  "generated_at": "2026-08-27T05:27:14.722635+00:00",
  "meta_learner": {
    "delta_vs_tier1_alone": {
      "delta": -0.032157,
      "interval": [
        -0.037348,
        -0.027291
      ],
      "verdict": "excludes zero"
    },
    "model_id": "meta-learner-xgboost-ieee-cis-20260824t145659z",
    "notes": [
      "Supersedes every earlier meta_learner entry: meta-learner-xgboost-ieee-cis-20260824t100225z (a calibrator fitted on the probability scale and applied to margins, so every probability and threshold in it is an artefact, uninterpretable calibration, a Tier-1 baseline thresholded on the test split, a quantisation-damaged Tier-1 baseline, a retirement sentence claiming an interval does not exclude zero when it excludes zero negatively); meta-learner-xgboost-ieee-cis-20260824t104214z (a calibrator fitted on the probability scale and applied to margins, so every probability and threshold in it is an artefact, uninterpretable calibration, a Tier-1 baseline thresholded on the test split, a retirement sentence claiming an interval does not exclude zero when it excludes zero negatively); meta-learner-xgboost-ieee-cis-20260824t133619z (a calibrator fitted on the probability scale and applied to margins, so every probability and threshold in it is an artefact, uninterpretable calibration, a retirement sentence claiming an interval does not exclude zero when it excludes zero negatively); meta-learner-xgboost-ieee-cis-20260824t141902z (a retirement sentence claiming an interval does not exclude zero when it excludes zero negatively). The registry is append-only, so those entries remain, carrying the defects they were produced with and no forward pointer of their own. Supersession can only be recorded forward, and this is that record. Treat any threshold-dependent figure in them as an artefact of the defect named beside it.",
      "Headline against Tier-1 alone: -0.0322, 95% CI [-0.0373, -0.0273] -- the interval excludes zero.",
      "Out-of-fold Tier-1: 5 forward-chaining blocks over the train split, block 1 dropped (no predecessor to score it), 1917 rounds per fold fixed from the registered model's best_iteration, each fold refitting its own input spec. Fold feature versions: ['fv_96aa13d9cceb', 'fv_f6f707927a5c', 'fv_63961b99aeab', 'fv_20845ba7bb4e'].",
      "engineered: retained (base block, exempt from retirement).",
      "tier1: retained (base block, exempt from retirement).",
      "tier2: retired for want of evidence at n=31,003 (1,131 positives) -- best add_one delta +0.0012, 95% CI [-0.0011, +0.0035], width 0.0046. The interval does not exclude zero, which is an absence of evidence that this layer helps, not evidence that it does not.",
      "tier3_served: retired for want of evidence at n=31,003 (1,131 positives) -- best leave_one_out delta -0.0001, 95% CI [-0.0030, +0.0032], width 0.0062. The interval does not exclude zero, which is an absence of evidence that this layer helps, not evidence that it does not.",
      "tier3_topology: retired -- leave_one_out delta -0.0061, 95% CI [-0.0100, -0.0026], which excludes zero on the NEGATIVE side at n=31,003 (1,131 positives). This block measurably degrades the model; removing it is an improvement, not merely a simplification.",
      "Keep/drop was arbitrated on the V-arb validation slice, where no tier signal is in-sample. The train-fit column is reported alongside; the disagreement between the two is the measured size of Tier-2's train contamination.",
      "Tier-2's latent size, window and early-stopping round were all selected on validation, so validation flatters Tier-2 relative to test. A drop verdict is therefore safe (it lost with a thumb on the scale); a keep verdict is suggestive rather than conclusive.",
      "Tier-1's round count was early-stopped on the full validation split during Phase 2, so all three validation slices carry one Tier-1 hyperparameter tuned on them. It is one scalar over 88,581 rows and cannot be undone without retraining Tier-1.",
      "tier3_topology is not obtainable from a Tier3Result today. If it was retained above, serving it is a Phase 7 requirement: Tier-3's persisted score table must carry a per-account feature vector.",
      "Not fitted on PaySim. Its Tier-1 PR-AUC of 0.9999 is a simulator artefact (amount == oldbalanceOrg on 97.49% of fraud), it has no Tier-2 model, and Tier-3 abstains on 100% of its test transactions. See BUILD_LOG.md Phase 2 finding 3.",
      "top_features is an evasion oracle: authenticated internal reviewers only, never returned to the transacting party.",
      "Tier-2 memorisation diagnostic: {'included_clean_rows': 35899, 'excluded_clean_rows': 28569, 'fraud_rows': 5856, 'memorisation_auc': 0.950091, 'fraud_auc': 0.862818, 'residual_auc': 0.364853}.",
      "Tier-3 circularity control: The control uses fingerprints sharing no column with the constructed account_id, at a MATCHED entity cap of 200. Phase 4 defect B5 recorded its own control as confounded by a mismatched cap (main 200 against control 50); matching it here closes that defect rather than inheriting it."
    ],
    "pr_auc": 0.495416,
    "pr_auc_ci95": [
      0.479087,
      0.51408
    ]
  },
  "registry_sha256": "f8de26987889cb50",
  "tier1": {
    "base_rate": 0.034804,
    "capacity_constrained_operating_point": {
      "base_rate": 0.034804,
      "confusion_matrix": {
        "fn": 2324,
        "fp": 110,
        "tn": 85388,
        "tp": 759
      },
      "f1": 0.384109,
      "false_positive_cost": {
        "assumptions": [
          "Cost is linear in the number of mistakes: no queue-congestion effect, no customer-churn effect from repeated false declines, no recovery on disputed fraud. All three would raise the true cost of a false positive.",
          "Every fraud is assumed to charge back. In practice some share is never disputed, which would lower false-negative cost.",
          "Review capacity is unbounded. This is the assumption that bites hardest: the cost-minimising threshold below flags whatever share of traffic the arithmetic favours, with no ceiling on the queue it implies."
        ],
        "cost_per_1000_transactions": 4922.4986,
        "false_negative_cost": 435709.85,
        "false_negatives": 2324,
        "false_positive_cost": 330.0,
        "false_positives": 110,
        "flag_rate": 0.00981,
        "flagged": 869,
        "total_cost": 436039.85,
        "units": "IEEE-CIS amount units (consistent with USD)"
      },
      "lift_over_no_skill": 15.158,
      "model": "LightGBM (full inputs) @ capacity",
      "notes": [
        "The same model at a staffable operating point. Reported because the cost-minimising threshold above assumes unbounded review capacity."
      ],
      "positives": 3083,
      "pr_auc": 0.527572,
      "pr_auc_no_skill_floor": 0.034804,
      "precision": 0.873418,
      "recall": 0.246189,
      "rows": 88581,
      "split": "test"
    },
    "confusion_matrix": {
      "fn": 379,
      "fp": 22924,
      "tn": 62574,
      "tp": 2704
    },
    "f1": 0.18836,
    "false_positive_cost": {
      "assumptions": [
        "Cost is linear in the number of mistakes: no queue-congestion effect, no customer-churn effect from repeated false declines, no recovery on disputed fraud. All three would raise the true cost of a false positive.",
        "Every fraud is assumed to charge back. In practice some share is never disputed, which would lower false-negative cost.",
        "Review capacity is unbounded. This is the assumption that bites hardest: the cost-minimising threshold below flags whatever share of traffic the arithmetic favours, with no ceiling on the queue it implies."
      ],
      "cost_per_1000_transactions": 1362.0593,
      "false_negative_cost": 51880.57,
      "false_negatives": 379,
      "false_positive_cost": 68772.0,
      "false_positives": 22924,
      "flag_rate": 0.289317,
      "flagged": 25628,
      "total_cost": 120652.57,
      "units": "IEEE-CIS amount units (consistent with USD)"
    },
    "feature_version": "fv_c1d8eb96f693",
    "model_id": "tier1-anomaly-lightgbm-ieee-cis-20260822t185154z",
    "positives": 3083,
    "pr_auc": 0.527572,
    "pr_auc_ci95": [
      0.511655,
      0.546153
    ],
    "pr_auc_no_skill_floor": 0.034804,
    "pr_curve": {
      "base_rate": 0.034804,
      "n": 88581,
      "points": [
        {
          "precision": 0.034804,
          "recall": 1.0
        },
        {
          "precision": 0.034979,
          "recall": 1.0
        },
        {
          "precision": 0.035144,
          "recall": 0.999676
        },
        {
          "precision": 0.035299,
          "recall": 0.999027
        },
        {
          "precision": 0.035433,
          "recall": 0.997729
        },
        {
          "precision": 0.035615,
          "recall": 0.997729
        },
        {
          "precision": 0.035787,
          "recall": 0.997405
        },
        {
          "precision": 0.035948,
          "recall": 0.996756
        },
        {
          "precision": 0.036124,
          "recall": 0.996432
        },
        {
          "precision": 0.036301,
          "recall": 0.996108
        },
        {
          "precision": 0.036468,
          "recall": 0.995459
        },
        {
          "precision": 0.036625,
          "recall": 0.994486
        },
        {
          "precision": 0.03682,
          "recall": 0.994486
        },
        {
          "precision": 0.037004,
          "recall": 0.994162
        },
        {
          "precision": 0.037179,
          "recall": 0.993513
        },
        {
          "precision": 0.03738,
          "recall": 0.993513
        },
        {
          "precision": 0.03757,
          "recall": 0.993188
        },
        {
          "precision": 0.037775,
          "recall": 0.993188
        },
        {
          "precision": 0.03797,
          "recall": 0.992864
        },
        {
          "precision": 0.03818,
          "recall": 0.992864
        },
        {
          "precision": 0.03838,
          "recall": 0.99254
        },
        {
          "precision": 0.038558,
          "recall": 0.991567
        },
        {
          "precision": 0.038776,
          "recall": 0.991567
        },
        {
          "precision": 0.038974,
          "recall": 0.990918
        },
        {
          "precision": 0.039183,
          "recall": 0.990594
        },
        {
          "precision": 0.039396,
          "recall": 0.990269
        },
        {
          "precision": 0.039584,
          "recall": 0.989296
        },
        {
          "precision": 0.039814,
          "recall": 0.989296
        },
        {
          "precision": 0.040033,
          "recall": 0.988972
        },
        {
          "precision": 0.040263,
          "recall": 0.988647
        },
        {
          "precision": 0.040461,
          "recall": 0.987674
        },
        {
          "precision": 0.040695,
          "recall": 0.987026
        },
        {
          "precision": 0.04092,
          "recall": 0.986377
        },
        {
          "precision": 0.041162,
          "recall": 0.986053
        },
        {
          "precision": 0.041436,
          "recall": 0.986053
        },
        {
          "precision": 0.041666,
          "recall": 0.985404
        },
        {
          "precision": 0.041913,
          "recall": 0.985079
        },
        {
          "precision": 0.042179,
          "recall": 0.985079
        },
        {
          "precision": 0.042432,
          "recall": 0.984755
        },
        {
          "precision": 0.042686,
          "recall": 0.984431
        },
        {
          "precision": 0.042961,
          "recall": 0.984106
        },
        {
          "precision": 0.043209,
          "recall": 0.983458
        },
        {
          "precision": 0.043487,
          "recall": 0.983458
        },
        {
          "precision": 0.043745,
          "recall": 0.982809
        },
        {
          "precision": 0.044018,
          "recall": 0.982485
        },
        {
          "precision": 0.044314,
          "recall": 0.98216
        },
        {
          "precision": 0.044608,
          "recall": 0.98216
        },
        {
          "precision": 0.044881,
          "recall": 0.981512
        },
        {
          "precision": 0.045174,
          "recall": 0.981187
        },
        {
          "precision": 0.045485,
          "recall": 0.981187
        },
        {
          "precision": 0.045802,
          "recall": 0.981187
        },
        {
          "precision": 0.046116,
          "recall": 0.981187
        },
        {
          "precision": 0.046415,
          "recall": 0.980863
        },
        {
          "precision": 0.046745,
          "recall": 0.980863
        },
        {
          "precision": 0.047073,
          "recall": 0.980863
        },
        {
          "precision": 0.047369,
          "recall": 0.980214
        },
        {
          "precision": 0.047684,
          "recall": 0.979565
        },
        {
          "precision": 0.048006,
          "recall": 0.979241
        },
        {
          "precision": 0.048335,
          "recall": 0.978917
        },
        {
          "precision": 0.04867,
          "recall": 0.978592
        },
        {
          "precision": 0.04902,
          "recall": 0.978592
        },
        {
          "precision": 0.049345,
          "recall": 0.977944
        },
        {
          "precision": 0.049673,
          "recall": 0.977295
        },
        {
          "precision": 0.050022,
          "recall": 0.97697
        },
        {
          "precision": 0.050345,
          "recall": 0.975997
        },
        {
          "precision": 0.050686,
          "recall": 0.975349
        },
        {
          "precision": 0.051054,
          "recall": 0.975024
        },
        {
          "precision": 0.051425,
          "recall": 0.9747
        },
        {
          "precision": 0.051817,
          "recall": 0.9747
        },
        {
          "precision": 0.052198,
          "recall": 0.974376
        },
        {
          "precision": 0.052585,
          "recall": 0.974051
        },
        {
          "precision": 0.052926,
          "recall": 0.972754
        },
        {
          "precision": 0.053325,
          "recall": 0.972429
        },
        {
          "precision": 0.053677,
          "recall": 0.971132
        },
        {
          "precision": 0.05407,
          "recall": 0.970483
        },
        {
          "precision": 0.05447,
          "recall": 0.969835
        },
        {
          "precision": 0.054913,
          "recall": 0.969835
        },
        {
          "precision": 0.055289,
          "recall": 0.968537
        },
        {
          "precision": 0.055709,
          "recall": 0.967888
        },
        {
          "precision": 0.05606,
          "recall": 0.965942
        },
        {
          "precision": 0.056493,
          "recall": 0.965294
        },
        {
          "precision": 0.056895,
          "recall": 0.963996
        },
        {
          "precision": 0.057343,
          "recall": 0.963347
        },
        {
          "precision": 0.057818,
          "recall": 0.963023
        },
        {
          "precision": 0.058301,
          "recall": 0.962699
        },
        {
          "precision": 0.058693,
          "recall": 0.960753
        },
        {
          "precision": 0.059213,
          "recall": 0.960753
        },
        {
          "precision": 0.059681,
          "recall": 0.959779
        },
        {
          "precision": 0.060157,
          "recall": 0.958806
        },
        {
          "precision": 0.060643,
          "recall": 0.957833
        },
        {
          "precision": 0.061137,
          "recall": 0.95686
        },
        {
          "precision": 0.061621,
          "recall": 0.955563
        },
        {
          "precision": 0.062154,
          "recall": 0.954914
        },
        {
          "precision": 0.06272,
          "recall": 0.95459
        },
        {
          "precision": 0.063295,
          "recall": 0.954265
        },
        {
          "precision": 0.063839,
          "recall": 0.953292
        },
        {
          "precision": 0.064327,
          "recall": 0.951346
        },
        {
          "precision": 0.064935,
          "recall": 0.951022
        },
        {
          "precision": 0.065533,
          "recall": 0.950373
        },
        {
          "precision": 0.066052,
          "recall": 0.948427
        },
        {
          "precision": 0.066674,
          "recall": 0.947778
        },
        {
          "precision": 0.067261,
          "recall": 0.946481
        },
        {
          "precision": 0.067909,
          "recall": 0.945832
        },
        {
          "precision": 0.068474,
          "recall": 0.943886
        },
        {
          "precision": 0.069124,
          "recall": 0.942913
        },
        {
          "precision": 0.069836,
          "recall": 0.942588
        },
        {
          "precision": 0.070464,
          "recall": 0.940967
        },
        {
          "precision": 0.071187,
          "recall": 0.940318
        },
        {
          "precision": 0.071893,
          "recall": 0.939345
        },
        {
          "precision": 0.072517,
          "recall": 0.937074
        },
        {
          "precision": 0.073178,
          "recall": 0.935128
        },
        {
          "precision": 0.073959,
          "recall": 0.934479
        },
        {
          "precision": 0.074652,
          "recall": 0.932533
        },
        {
          "precision": 0.075389,
          "recall": 0.930911
        },
        {
          "precision": 0.076171,
          "recall": 0.929614
        },
        {
          "precision": 0.077022,
          "recall": 0.928965
        },
        {
          "precision": 0.077876,
          "recall": 0.927992
        },
        {
          "precision": 0.078659,
          "recall": 0.926046
        },
        {
          "precision": 0.07941,
          "recall": 0.923451
        },
        {
          "precision": 0.080177,
          "recall": 0.920856
        },
        {
          "precision": 0.081195,
          "recall": 0.920856
        },
        {
          "precision": 0.082235,
          "recall": 0.920856
        },
        {
          "precision": 0.083157,
          "recall": 0.919235
        },
        {
          "precision": 0.084012,
          "recall": 0.91664
        },
        {
          "precision": 0.085013,
          "recall": 0.915342
        },
        {
          "precision": 0.08601,
          "recall": 0.91372
        },
        {
          "precision": 0.086939,
          "recall": 0.911126
        },
        {
          "precision": 0.087865,
          "recall": 0.908206
        },
        {
          "precision": 0.088687,
          "recall": 0.90399
        },
        {
          "precision": 0.089859,
          "recall": 0.903017
        },
        {
          "precision": 0.090963,
          "recall": 0.90107
        },
        {
          "precision": 0.092135,
          "recall": 0.899449
        },
        {
          "precision": 0.093374,
          "recall": 0.898151
        },
        {
          "precision": 0.094516,
          "recall": 0.895556
        },
        {
          "precision": 0.095902,
          "recall": 0.894908
        },
        {
          "precision": 0.097186,
          "recall": 0.892961
        },
        {
          "precision": 0.098372,
          "recall": 0.889718
        },
        {
          "precision": 0.099519,
          "recall": 0.885825
        },
        {
          "precision": 0.101041,
          "recall": 0.884852
        },
        {
          "precision": 0.102534,
          "recall": 0.883231
        },
        {
          "precision": 0.103891,
          "recall": 0.879987
        },
        {
          "precision": 0.105368,
          "recall": 0.877392
        },
        {
          "precision": 0.10702,
          "recall": 0.87577
        },
        {
          "precision": 0.108569,
          "recall": 0.872851
        },
        {
          "precision": 0.110417,
          "recall": 0.871878
        },
        {
          "precision": 0.111962,
          "recall": 0.867986
        },
        {
          "precision": 0.113688,
          "recall": 0.865066
        },
        {
          "precision": 0.115485,
          "recall": 0.862147
        },
        {
          "precision": 0.117126,
          "recall": 0.857606
        },
        {
          "precision": 0.119154,
          "recall": 0.855336
        },
        {
          "precision": 0.121167,
          "recall": 0.852416
        },
        {
          "precision": 0.123129,
          "recall": 0.848524
        },
        {
          "precision": 0.125222,
          "recall": 0.844956
        },
        {
          "precision": 0.127548,
          "recall": 0.842361
        },
        {
          "precision": 0.12938,
          "recall": 0.835874
        },
        {
          "precision": 0.131649,
          "recall": 0.831657
        },
        {
          "precision": 0.134188,
          "recall": 0.828414
        },
        {
          "precision": 0.136787,
          "recall": 0.824846
        },
        {
          "precision": 0.139409,
          "recall": 0.820629
        },
        {
          "precision": 0.141873,
          "recall": 0.814791
        },
        {
          "precision": 0.144827,
          "recall": 0.810898
        },
        {
          "precision": 0.147681,
          "recall": 0.805709
        },
        {
          "precision": 0.150586,
          "recall": 0.79987
        },
        {
          "precision": 0.153894,
          "recall": 0.795329
        },
        {
          "precision": 0.157382,
          "recall": 0.790788
        },
        {
          "precision": 0.161616,
          "recall": 0.788842
        },
        {
          "precision": 0.164864,
          "recall": 0.781057
        },
        {
          "precision": 0.168608,
          "recall": 0.77457
        },
        {
          "precision": 0.172655,
          "recall": 0.768407
        },
        {
          "precision": 0.17706,
          "recall": 0.762569
        },
        {
          "precision": 0.18191,
          "recall": 0.757379
        },
        {
          "precision": 0.18688,
          "recall": 0.751216
        },
        {
          "precision": 0.192385,
          "recall": 0.745702
        },
        {
          "precision": 0.198123,
          "recall": 0.739539
        },
        {
          "precision": 0.204609,
          "recall": 0.73435
        },
        {
          "precision": 0.211051,
          "recall": 0.727214
        },
        {
          "precision": 0.218369,
          "recall": 0.721051
        },
        {
          "precision": 0.226843,
          "recall": 0.71651
        },
        {
          "precision": 0.235395,
          "recall": 0.709698
        },
        {
          "precision": 0.244663,
          "recall": 0.702562
        },
        {
          "precision": 0.253746,
          "recall": 0.692183
        },
        {
          "precision": 0.263713,
          "recall": 0.681479
        },
        {
          "precision": 0.274419,
          "recall": 0.669802
        },
        {
          "precision": 0.288195,
          "recall": 0.662018
        },
        {
          "precision": 0.301054,
          "recall": 0.648394
        },
        {
          "precision": 0.317412,
          "recall": 0.638015
        },
        {
          "precision": 0.334666,
          "recall": 0.624716
        },
        {
          "precision": 0.354857,
          "recall": 0.611417
        },
        {
          "precision": 0.378029,
          "recall": 0.597146
        },
        {
          "precision": 0.407274,
          "recall": 0.58482
        },
        {
          "precision": 0.436998,
          "recall": 0.56471
        },
        {
          "precision": 0.472614,
          "recall": 0.542978
        },
        {
          "precision": 0.518232,
          "recall": 0.520921
        },
        {
          "precision": 0.565299,
          "recall": 0.487188
        },
        {
          "precision": 0.623306,
          "recall": 0.447616
        },
        {
          "precision": 0.695824,
          "recall": 0.399935
        },
        {
          "precision": 0.776524,
          "recall": 0.334739
        },
        {
          "precision": 0.864713,
          "recall": 0.248784
        },
        {
          "precision": 0.907658,
          "recall": 0.130717
        },
        {
          "precision": 1.0,
          "recall": 0.000324
        }
      ],
      "positives": 3083
    },
    "precision": 0.10551,
    "recall": 0.877068,
    "rows": 88581
  },
  "tier3": {
    "base_rate": 0.107681,
    "confusion_matrix": {
      "fn": 127,
      "fp": 2,
      "tn": 1183,
      "tp": 16
    },
    "false_positive_cost": {
      "assumptions": [
        "Cost is linear in the number of mistakes: no queue-congestion effect, no customer-churn effect from repeated false declines, no recovery on disputed fraud. All three would raise the true cost of a false positive.",
        "Every fraud is assumed to charge back. In practice some share is never disputed, which would lower false-negative cost.",
        "Review capacity is unbounded. This is the assumption that bites hardest: the cost-minimising threshold below flags whatever share of traffic the arithmetic favours, with no ceiling on the queue it implies."
      ],
      "cost_per_1000_rings": 2440192.4792,
      "false_negative_cost": 3240545.61,
      "false_negatives": 127,
      "false_positive_cost": 30.0,
      "false_positives": 2,
      "flag_rate": 0.013554,
      "flagged": 18,
      "total_cost": 3240575.61,
      "unit": "ring",
      "units": "IEEE-CIS amount units (consistent with USD)"
    },
    "model_id": "tier3-graph-louvain-ieee-cis-20260826t213613z",
    "positives": 143,
    "pr_auc": 0.646543,
    "pr_auc_ci95": [
      0.570037,
      0.717075
    ],
    "pr_auc_no_skill_floor": 0.107681,
    "rows": 1328,
    "unit_of_analysis": "ring"
  }
}
